steal(
    '//lib/jquery-2.1.0/jquery-2.1.0.js',
    '//lib/angular/angular.js',
    '//lib/bootstrap-3.1.1-dist/css/bootstrap.css'
).then(
    '//lib/bootstrap-3.1.1-dist/js/bootstrap.js',
    '//lib/angular/angular-route.js',
    '//lib/frog/bootstrap.js'
);